"""
main.py — DRM Guard FastAPI Backend
=====================================
Entry point for the backend API server.

Run in development:
    uvicorn main:app --reload --host 0.0.0.0 --port 8000

API Docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc

Architecture:
    /auth/*   — Creator registration & JWT login
    /files/*  — DRM file policy management (creator-authenticated)
    /kms/*    — AES key issuance for the desktop client (MAC-validated)
    /audit/*  — Access log viewer (creator-authenticated)
"""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from config import get_settings
from database import init_db
from routers.auth_router  import router as auth_router
from routers.files_router import router as files_router
from routers.kms_router   import router as kms_router
from routers.audit_router import router as audit_router

# ─── Logging ─────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger("drm_guard")

settings = get_settings()


# ─── Lifespan (startup / shutdown) ───────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs on server startup:
      - Creates all database tables (SQLite dev mode).
      - For PostgreSQL production, use Alembic migrations instead.
    """
    logger.info("Starting DRM Guard API server...")
    await init_db()
    logger.info("Database tables initialized.")
    yield
    logger.info("Shutting down DRM Guard API server.")


# ─── App ─────────────────────────────────────────────────────────────────────
app = FastAPI(
    title       = "DRM Guard API",
    description = (
        "Backend Key Management System (KMS) for DRM Guard.\n\n"
        "**Creator dashboard** endpoints are JWT-authenticated (Bearer token).\n\n"
        "**Desktop client** (KMS key request) uses file_id + MAC address authentication."
    ),
    version     = "2.0.0",
    contact     = {
        "name":  "Charan",
        "url":   "https://github.com/Charan291005/DRM-APP",
    },
    license_info= {"name": "MIT"},
    lifespan    = lifespan,
    docs_url    = "/docs",
    redoc_url   = "/redoc",
)


# ─── CORS ────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins     = settings.allowed_origins_list,
    allow_credentials = True,
    allow_methods     = ["*"],
    allow_headers     = ["*"],
)


# ─── Routers ─────────────────────────────────────────────────────────────────
app.include_router(auth_router)
app.include_router(files_router)
app.include_router(kms_router)
app.include_router(audit_router)


# ─── Health Check ────────────────────────────────────────────────────────────
@app.get("/", tags=["Health"], summary="Health check")
async def root():
    return {
        "service": "DRM Guard API",
        "version": "2.0.0",
        "status":  "ok",
        "docs":    "/docs",
    }


@app.get("/health", tags=["Health"], summary="Detailed health check")
async def health():
    return JSONResponse(content={"status": "healthy", "db": "connected"})


# ─── Dev entry point ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host    = settings.HOST,
        port    = settings.PORT,
        reload  = True,
        log_level = "info",
    )
